# BIENVENU ! MODIFIER ICI LES PARAMETRES DE VOTRE PLATEFORME KATALOG
# -------------------------------------------------


# NAVIGATION
# -------------------------------------------------

nav:

  - Accueil: index.md
  
  - Sophrologie ?: pages/informations/sophrologie.md
  
  - Séances: pages/seances/accueil.md
  
  - Ateliers: pages/ateliers/accueil.md
  
  - Accompagnements spécifiques: pages/accompagnements/accueil.md
  
  - Blog:
  
      - Mieux comprendre la sophrologie: pages/blog/sophro_intro.md
      
  - Contacts: pages/informations/contacts.md
      




# SITE INFORMATIONS 
# -------------------------------------------------

site_name: Matheyzen - Sophrologie et Harmonie
site_author: Nicolas Brémond
site_description: Envie de retrouver calme, confiance, harmonie et optimisme ?  De se projeter avec regard positif sur sa vie et les autres ? La sophrologie caycédienne peut vous y aider.
site_url: https://besnardl.github.io/website
repo_url: https://github.com/besnardl/website

extra:
  katalog_repo: "https://github.com/besnardl/website"
  katalog_site: "https://besnardl.github.io/website"
  katalog_mdp: "sophro"
  

# LANGUE, COULEURS et LOGO
#
# [Liste des couleurs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color)
# -------------------------------------------------

theme:
    language: fr
    palette:
        primary: white
        accent: purple
    logo: https://user-images.githubusercontent.com/113187227/214503137-f2dfe3ee-5949-41a7-8e68-cca6b27b5759.png
    favicon: https://user-images.githubusercontent.com/113187227/214500518-2af76e9b-7a04-429d-b6c8-d9c426d3c8ed.png



# MENTIONS 
# -------------------------------------------------

copyright: Sophrologie en Matheysine par Corinne Grignou - site Web développé avec ❤ par Konsilion


# /!\   NE PAS MODIFIER CI-DESSOUS   /!\
# -------------------------------------------------
INHERIT: ./docs/admin/env
