# BIENVENU ! MODIFIER ICI LES PARAMETRES DE VOTRE PLATEFORME KATALOG
# -------------------------------------------------


# NAVIGATION
# -------------------------------------------------

nav:

    - Accueil: index.md
            
    - Ingénierie collaborative:

        - De quoi parlons nous ?: pages/presentation.md

        - Katalog - CMS: pages/katalog.md

        - Konnect - DataScience: https://konnect.konsilion.fr

    - Recherche & Développement:

        - Projets: katalog/projets/home.md

        - Tâches: katalog/taches/home.md

        - Ressources: katalog/ressources/home.md
        
    - À propos: pages/informations.md



# SITE INFORMATIONS 
# -------------------------------------------------

site_name: Matheyzen - Sophrologie et Harmonie
site_author: Nicolas Brémond
site_description: Développer, proposer et promouvoir la Low-technologie.
site_url: https://besnardl.github.io/website
repo_url: https://github.com/besnardl/website

extra:
  katalog_repo: "https://github.com/besnardl/website"
  katalog_site: "https://besnardl.github.io/website"
  katalog_mdp: "sophro"
  

# LANGUE, COULEURS et LOGO
#
# [Liste des couleurs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color)
# -------------------------------------------------

theme:
    language: fr
    palette:
        primary: white
        accent: blue
    logo: https://user-images.githubusercontent.com/113187227/214500518-2af76e9b-7a04-429d-b6c8-d9c426d3c8ed.png
    favicon: https://user-images.githubusercontent.com/113187227/214500518-2af76e9b-7a04-429d-b6c8-d9c426d3c8ed.png



# MENTIONS 
# -------------------------------------------------

copyright: Un site Web développé avec ❤ par Konsilion


# /!\   NE PAS MODIFIER CI-DESSOUS   /!\
# -------------------------------------------------
INHERIT: ./docs/admin/env
